package com.curso.hibernate.app_Hibernate.Modelos;
// Generated 05-may-2016 15:33:09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AppUsers generated by hbm2java
 */
public class AppUsers implements java.io.Serializable {

	private Long id;
	private String ssoId;
	private String firstName;
	private String lastName;
	private String email;
	private Set userDocuments = new HashSet(0);

	public AppUsers() {
	}

	public AppUsers(String ssoId, String firstName, String lastName, String email) {
		this.ssoId = ssoId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
	}

	public AppUsers(String ssoId, String firstName, String lastName, String email, Set userDocuments) {
		this.ssoId = ssoId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.userDocuments = userDocuments;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSsoId() {
		return this.ssoId;
	}

	public void setSsoId(String ssoId) {
		this.ssoId = ssoId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getUserDocuments() {
		return this.userDocuments;
	}

	public void setUserDocuments(Set userDocuments) {
		this.userDocuments = userDocuments;
	}

}
