package com.curso.hibernate.app_Hibernate.Modelos;
// Generated 21-ene-2016 11:09:51 by Hibernate Tools 3.4.0.CR1



/**
 * Producto generated by hbm2java
 */



public class Producto implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idProducto;
	private Cliente cliente;
	private String nombre;
	private int cantidades;
	private double   cantidadesDoble;	
	public Double getDfdf() {
		return dfdf;
	}

	public void setDfdf(Double dfdf) {
		this.dfdf = dfdf;
	}

	Double dfdf = new Double(0);

	public double getCantidadesDoble() {
		return cantidadesDoble;
	}

	public void setCantidadesDoble(double cantidadesDoble) {
		this.cantidadesDoble = cantidadesDoble;
	}

	public Producto() {
	}

	public Producto(Cliente cliente, String nombre, int cantidades) {
		this.cliente = cliente;
		this.nombre = nombre;
		this.cantidades = cantidades;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getCantidades() {
		return this.cantidades;
	}

	public void setCantidades(int cantidades) {
		this.cantidades = cantidades;
	}

}
