package com.curso.hibernate.app_Hibernate.Modelos;
// Generated 05-may-2016 15:33:09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UserProfile generated by hbm2java
 */
public class UserProfile implements java.io.Serializable {

	private Long id;
	private String type;
	private Set appUsers = new HashSet(0);

	public UserProfile() {
	}

	public UserProfile(String type) {
		this.type = type;
	}

	public UserProfile(String type, Set appUsers) {
		this.type = type;
		this.appUsers = appUsers;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getAppUsers() {
		return this.appUsers;
	}

	public void setAppUsers(Set appUsers) {
		this.appUsers = appUsers;
	}

}
