package com.curso.hibernate.app_Hibernate.Modelos;
// Generated 05-may-2016 15:33:09 by Hibernate Tools 3.4.0.CR1

/**
 * UserDocument generated by hbm2java
 */
public class UserDocument implements java.io.Serializable {

	private Long id;
	private AppUsers appUsers;
	private String name;
	private String description;
	private String type;
	private byte[] content;

	public UserDocument() {
	}

	public UserDocument(AppUsers appUsers, String name, String type, byte[] content) {
		this.appUsers = appUsers;
		this.name = name;
		this.type = type;
		this.content = content;
	}

	public UserDocument(AppUsers appUsers, String name, String description, String type, byte[] content) {
		this.appUsers = appUsers;
		this.name = name;
		this.description = description;
		this.type = type;
		this.content = content;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public AppUsers getAppUsers() {
		return this.appUsers;
	}

	public void setAppUsers(AppUsers appUsers) {
		this.appUsers = appUsers;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

}
