package com.curso.hibernate.app_Hibernate.Modelos;
// Generated 21-ene-2016 11:09:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private Integer idCliente;
	private String nombre;
	private String apellidos;
	private Set productos = new HashSet(0);
	private Direccion direccion;
	private Set correoelectronicos = new HashSet(0);

	public Cliente() {
	}

	public Cliente(String nombre, String apellidos) {
		this.nombre = nombre;
		this.apellidos = apellidos;
	}

	public Cliente(String nombre, String apellidos, Set productos, Direccion direccion, Set correoelectronicos) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.productos = productos;
		this.direccion = direccion;
		this.correoelectronicos = correoelectronicos;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

	public Direccion getDireccion() {
		return this.direccion;
	}

	public void setDireccion(Direccion direccion) {
		this.direccion = direccion;
	}

	public Set getCorreoelectronicos() {
		return this.correoelectronicos;
	}

	public void setCorreoelectronicos(Set correoelectronicos) {
		this.correoelectronicos = correoelectronicos;
	}

}
