package com.curso.hibernate.app_Hibernate.Modelos;
// Generated 21-ene-2016 11:09:51 by Hibernate Tools 3.4.0.CR1

/**
 * Direccion generated by hbm2java
 */
public class Direccion implements java.io.Serializable {

	private Integer idCliente;
	private Cliente cliente;
	private String calle;
	private String dp;
	private String poblacion;
	private String provincia;

	public Direccion() {
	}

	public Direccion(Cliente cliente, String calle, String poblacion, String provincia) {
		this.cliente = cliente;
		this.calle = calle;
		this.poblacion = poblacion;
		this.provincia = provincia;
	}

	public Direccion(Cliente cliente, String calle, String dp, String poblacion, String provincia) {
		this.cliente = cliente;
		this.calle = calle;
		this.dp = dp;
		this.poblacion = poblacion;
		this.provincia = provincia;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public String getDp() {
		return this.dp;
	}

	public void setDp(String dp) {
		this.dp = dp;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

}
